name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t stormpijnenburg/docker-extra:${{ github.sha }} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push stormpijnenburg/docker-extra:${{ github.sha }}
